
import CardItem from "./components/cardItem"

export const metadata = {
  title: 'Главная',
  description: 'Generated by create next app',
}


export default function Home() {
  return (
    <main>
      <div className="container mx-auto my-5">

        <CardItem />
      
      </div>
    </main>
  )
}
